 name: project_environment
 channels:
  - conda-forge
  - anaconda
 dependencies:
  - python=3.8
  - numpy=1.22.4
  - pip=21.2.4
  - scikit-learn=1.2.2
  - pandas>=1.0.5,<1.2
  - pip:
    - azure-ai-ml==1.12.1
    - azure-identity==1.15.0
    - mlflow==2.9.1
    - mlflow-skinny==2.8.0
    - azureml-mlflow==1.51.0
    - matplotlib==3.1.3
    - joblib==1.1.1 
    - imbalanced-learn==0.11.0
    - azureml-core
    - azureml-dataset-runtime[fuse]
     
  