channels:
- conda-forge
dependencies:
- python=3.8.18
- pip<=21.2.4
- pip:
  - mlflow==2.8.0
  - cloudpickle==2.2.1
  - numpy==1.21.2
  - packaging==23.2
  - psutil==5.9.0
  - pyyaml==6.0.1
  - scikit-learn==1.0.2
  - scipy==1.10.1
name: mlflow-env
