# Permissions necessary to use the Azure/login action.
# Even if you grant read/write at the repo level, you still need id-token.
permissions:
    contents: read
    pages: write
    id-token: write
    
name: PROD - Train Model
    
on:
    workflow_dispatch:
      inputs: {}
    push:
      branches:
        - main
      paths:
        - src/model_training_to_deployment/**
        - .github/workflows/Deploy_train_prod.yml
  
jobs:
    deploy_ml_training_pipeline:
      name: PROD - Deploy the Training pipeline to Azure ML
      runs-on: ubuntu-latest
      environment: Production
      steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Install az CLI
        run: |
          # Install the az CLI and ML extension
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add -n ml -y
          echo "Installed Azure CLI and ML extension"
      - name: Debug Azure Credentials
        run: echo "${{ secrets.AZURE_CREDENTIALS }}"
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install and prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Create Azure ML Compute
        run: |
            cd setup/
            az ml compute create --file compute_cluster.yml --resource-group 220356622-rg --workspace-name MLOPS_project
      - name: Run AML pipeline
        run: |
          cd src/model_training_to_deployment/
          
          echo "Creating conda environment"
          conda env create -f conda.yml
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate project_environment

          echo "Creating config file"
          mkdir .azureml
          echo -e "{ \"subscription_id\": \"${{ secrets.ARM_SUBSCRIPTION_ID }}\", \"resource_group\": \"220356622-rg\", \"workspace_name\": \"MLOPS_project\" }" > .azureml/config.json
          
          echo "Run model training and deployment pipeline"
          # Run training to model deployment pipeline
          python Train_deploy_pipeline.py
