# Permissions necessary to use the Azure/login action.
# Even if you grant read/write at the repo level, you still need id-token.
permissions:
    contents: read
    pages: write
    id-token: write
    
name: PROD - Train Model
    
on:
    workflow_dispatch:
      inputs: {}
    push:
      branches:
        - main
      paths:
        - src/model_training_registration/**
        - src/model_training_registration/Train_reg_pipeline.py
        - .github/workflows/Deploy_train_prod.yml
  
jobs:
    deploy_ml_training_pipeline:
      name: PROD - Deploy the Training pipeline to Azure ML
      runs-on: ubuntu-latest
      environment: Production
      steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Install az CLI
        run: |
          # Install the az CLI and ML extension
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add -n ml -y
          echo "Installed Azure CLI and ML extension"
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          enable-AzPSSession: true
      - name: Install and prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Run AML pipeline
        run: |
          cd src/model_training_registration/
          echo "Creating conda environment"
          conda env create -f conda.yml
          conda activate project_environment
          echo "Creating config file"
          mkdir .azureml
          echo -e "{ \"subscription_id\": \"${{ secrets.AZURE_SUBSCRIPTION_ID }}\", \"resource_group\": \"CSAzureML\", \"workspace_name\": \"CSAzureML\" }" > .azureml/config.json
          echo "Run training pipeline"
          # Run training pipeline
          python Train_reg_pipeline.py
