# Permissions necessary to use the Azure/login action.
# Even if you grant read/write at the repo level, you still need id-token.
permissions:
    contents: read
    pages: write
    id-token: write
    
name: PROD - Scoring job
    
on:
    workflow_dispatch:
      inputs: {}
    push:
      branches:
        - main
      paths:
        - src/deployment/inf_data**
        - src/deployment/score_job.py
        - .github/workflows/score_prod.yml
  
jobs:
    deploy_ml_scoring_job:
      name: PROD Submit scoring job Azure ML
      runs-on: ubuntu-latest
      environment: Production
      steps:
      - name: Repo checkout
        uses: actions/checkout@v3
      - name: Install az CLI
        run: |
          # Install the az CLI and ML extension
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
          az extension add -n ml -y
          echo "Installed Azure CLI and ML extension"
      - name: Azure login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Install and prepare Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Create Azure ML Compute
        run: |
          cd setup/
          az ml compute create --file compute.yml --resource-group 220356622-rg --workspace-name MLOPS_project
      - name: Run AML pipeline
        run: |
          cd src/deployment/
          
          echo "Creating conda environment"
          conda env create -f conda.yml
          source $(conda info --base)/etc/profile.d/conda.sh
          conda activate project_environment
          
          echo "Creating config file"
          mkdir .azureml
          echo -e "{ \"subscription_id\": \"${{ secrets.ARM_SUBSCRIPTION_ID }}\", \"resource_group\": \"220356622-rg\", \"workspace_name\": \"MLOPS_project\" }" > .azureml/config.json
          
          echo "Run script for inferencing"
          # Submit scoring job 
          python score_job.py
